bug-fix: python wrapper missing unistring
import libdogecoin false: 
ImportError: .....build/lib.linux-x86_64-3.9/libdogecoin.cpython-39-x86_64-linux-gnu.so: undefined symbol: uninorm_nfkd


fix it